#!/usr/bin/env node
// Optional macOS menu bar via SwiftBar.
// Copies a plugin into SwiftBar's plugin folder that runs agent-menubar.mjs.

import { chmodSync, existsSync, mkdirSync, writeFileSync, readdirSync, unlinkSync } from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import { fileURLToPath } from 'node:url';
import { spawnSync } from 'node:child_process';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SCRIPT = path.join(ROOT, 'scripts', 'agent-menubar.mjs');
const PLUGIN_NAME = 'AgentControl.1m.sh';

const CANDIDATE_DIRS = [
  path.join(os.homedir(), 'Library', 'Application Support', 'SwiftBar'),
  path.join(os.homedir(), 'Library', 'Application Support', 'SwiftBar', 'Plugins'),
  path.join(os.homedir(), 'Documents', 'SwiftBarPlugins'),
];

function findSwiftBarPluginsDir() {
  // Prefer an existing Plugins subfolder, else create under Application Support/SwiftBar
  for (const dir of CANDIDATE_DIRS) {
    if (existsSync(dir)) return dir;
  }
  const fallback = path.join(os.homedir(), 'Library', 'Application Support', 'SwiftBar', 'Plugins');
  mkdirSync(fallback, { recursive: true });
  return fallback;
}

/** Drop prior AgentControl.*.sh plugins (e.g. .5m after a rename to .1m). */
function removeStalePlugins(pluginsDir, keepName) {
  let removed = [];
  try {
    for (const name of readdirSync(pluginsDir)) {
      if (/^AgentControl\..+\.sh$/.test(name) && name !== keepName) {
        unlinkSync(path.join(pluginsDir, name));
        removed.push(name);
      }
    }
  } catch {
    // ignore
  }
  return removed;
}

function swiftBarInstalled() {
  const apps = [
    '/Applications/SwiftBar.app',
    path.join(os.homedir(), 'Applications', 'SwiftBar.app'),
  ];
  if (apps.some((p) => existsSync(p))) return true;
  const which = spawnSync('mdfind', ['kMDItemCFBundleIdentifier == "com.ameba.SwiftBar"'], {
    encoding: 'utf8',
  });
  return Boolean(which.stdout?.trim());
}

const pluginsDir = findSwiftBarPluginsDir();
const pluginPath = path.join(pluginsDir, PLUGIN_NAME);
const removed = removeStalePlugins(pluginsDir, PLUGIN_NAME);

const wrapper = `#!/bin/bash
# AgentControl menu bar — generated by npm run install:menubar
# Refresh interval: 1 minute (filename .1m.)
set -euo pipefail
NODE="$(command -v node || true)"
if [[ -z "$NODE" && -x /opt/homebrew/bin/node ]]; then NODE=/opt/homebrew/bin/node; fi
if [[ -z "$NODE" && -x /usr/local/bin/node ]]; then NODE=/usr/local/bin/node; fi
if [[ -z "$NODE" ]]; then
  echo "AgentControl | sfimage=exclamationmark.triangle"
  echo "---"
  echo "node not found in PATH"
  exit 0
fi
exec "$NODE" ${JSON.stringify(SCRIPT)} --swiftbar
`;

writeFileSync(pluginPath, wrapper, { mode: 0o755 });
chmodSync(pluginPath, 0o755);

const pointerDir = path.join(os.homedir(), '.agentcontrol');
mkdirSync(pointerDir, { recursive: true });
writeFileSync(
  path.join(pointerDir, 'menubar-plugin-path.txt'),
  `${pluginPath}\n`,
);

// Seed JSON + Cursor-style HTML popover
spawnSync(process.execPath, [SCRIPT, '--html'], { stdio: 'ignore' });

console.log(`✓ SwiftBar plugin → ${pluginPath}`);
console.log(`  Click the menu title for the Agent Usage panel (webview popover).`);
console.log(`  Refreshes every 1 minute.`);
if (removed.length) {
  console.log(`  Removed stale plugin(s): ${removed.join(', ')}`);
}

if (!swiftBarInstalled()) {
  console.log(`
SwiftBar not detected. Install it, then point Plugins at:
  ${pluginsDir}

  brew install --cask swiftbar

Open SwiftBar → Preferences → Plugin Folder → select that directory (or restart SwiftBar).
`);
} else {
  console.log(`
SwiftBar looks installed. If the menu item is missing:
  1. SwiftBar → Preferences → ensure Plugin Folder includes:
     ${pluginsDir}
  2. SwiftBar → Refresh all
`);
}

console.log('Preview anytime:');
console.log(`  node ${SCRIPT} --swiftbar`);
console.log(`  open ~/.agentcontrol/menubar.html`);
